server:
  port: 8083
spring:
  application:
    name: catalog
  datasource:
    url: jdbc:h2:tcp://127.0.0.1:9091/${spring.application.name}
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    lazy-initialization: true
  output:
    ansi:
      enabled: always
